version: "3"

services:
    # Create keys:
    # - ./.acrakeys/acra-connector/${ACRA_CLIENT_ID}
    # - ./.acrakeys/acra-translator/${ACRA_CLIENT_ID}.pub
    acra-keymaker_connector:
        # You can specify docker image tag in the environment
        # variable ACRA_DOCKER_IMAGE_TAG or run by default with 'latest' images
        image: "cossacklabs/acra-keymaker:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        # We do not need network for keys' generation at all
        network_mode: "none"
        environment:
            # INSECURE!!! You MUST define your own ACRA_MASTER_KEY
            # The default is only for testing purposes
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        volumes:
            - ./.acrakeys:/keys
        command: >-
            --client_id=${ACRA_CLIENT_ID:-testclientid}
            --generate_acraconnector_keys
            --keys_output_dir=/keys/acra-connector
            --keys_public_output_dir=/keys/acra-translator
            --keystore=v1
    # Create keys:
    # - ./.acrakeys/acra-connector/${ACRA_CLIENT_ID}_translator.pub
    # - ./.acrakeys/acra-translator/${ACRA_CLIENT_ID}_translator
    acra-keymaker_translator:
        image: "cossacklabs/acra-keymaker:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        network_mode: "none"
        environment:
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        volumes:
            - ./.acrakeys:/keys
        command: >-
            --client_id=${ACRA_CLIENT_ID:-testclientid}
            --generate_acratranslator_keys
            --keys_output_dir=/keys/acra-translator
            --keys_public_output_dir=/keys/acra-connector
            --keystore=v1
    # Create keys:
    # - ./.acrakeys/acra-translator/${ACRA_CLIENT_ID}_storage
    # - ./.acrakeys/acra-writer/${ACRA_CLIENT_ID}_storage.pub
    acra-keymaker_writer:
        image: "cossacklabs/acra-keymaker:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        network_mode: "none"
        environment:
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        volumes:
            - ./.acrakeys:/keys
        command: >-
            --client_id=${ACRA_CLIENT_ID:-testclientid}
            --generate_acrawriter_keys
            --keys_output_dir=/keys/acra-translator
            --keys_public_output_dir=/keys/acra-writer
            --keystore=v1

    acra-translator:
        image: "cossacklabs/acra-translator:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        restart: always
        depends_on:
            - acra-keymaker_translator
            - acra-keymaker_connector
            - acra-keymaker_writer
        environment:
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        # We use internal networks:
        # - 'translator-connector' - for interconnection with AcraConnector
        networks:
            - translator-connector
        volumes:
            # Mount the directory with only the keys for this service
            - ./.acrakeys/acra-translator:/keys:ro
        command: >-
            --incoming_connection_grpc_string=http://0.0.0.0:9696
            --keys_dir=/keys
            --keystore_cache_size=100
            -v

    acra-connector:
        image: "cossacklabs/acra-connector:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        restart: always
        depends_on:
            - acra-keymaker_translator
            - acra-keymaker_connector
            - acra-translator
        # Open the port outside for client application
        ports:
            - "9494:9494"
        environment:
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        # We use internal networks:
        # - 'translator-connector' - for interconnection with AcraConnector
        # and external network 'world' for port exposing
        networks:
            - translator-connector
            - world
        volumes:
            # Mount the directory with only the keys for this service
            - ./.acrakeys/acra-connector:/keys:ro
        command: >-
            --mode=AcraTranslator
            --acratranslator_connection_host=acra-translator
            --acratranslator_connection_port=9696
            --client_id=${ACRA_CLIENT_ID:-testclientid}
            --incoming_connection_string=tcp://0.0.0.0:9494
            --keys_dir=/keys
            -v

networks:
    world:
    translator-connector:
        internal: true
