version: 0.85.0
# path to config
config_file: 

# log debug messages to stderr
d: false

# try migration without writing to the output key store
dry_run: false

# path to destination key directory (default ".acrakeys.migrated")
dst_keys_dir: 

# path to destination key directory for public keys (default ".acrakeys.migrated")
dst_keys_dir_public: 

# key store format to use: v1 (current), v2 (new)
dst_keystore: 

# dump config
dump_config: false

# write to output key store even if it exists
force: false

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# path to source key directory
src_keys_dir: .acrakeys

# path to source key directory for public keys
src_keys_dir_public: .acrakeys

# key store format to use: v1 (current), v2 (new)
src_keystore: 

# log everything to stderr
v: false

