- table: test
  columns:
  - id
  - data
  - raw_data
  encrypted:
  - column: data
    zone_id: DDDDDDDDMatNOMYjqVOuhACC

- table: test2
  columns:
  - id
  - zone
  - data
  - raw_data
  encrypted:
  - column: data
    client_id: client

    # use key by client_id from transport
  - column: raw_data