# path to config
config_file: 

# Turn on debug logging
d: false

# Host for AcraServer HTTP endpoint or AcraConnector
destination_host: localhost

# Port for AcraServer HTTP endpoint or AcraConnector
destination_port: 9191

# dump config
dump_config: false

# Mode for basic auth. Possible values: auth_on|auth_off_local|auth_off
http_auth_mode: auth_on

# Host for AcraWebconfig HTTP endpoint
incoming_connection_host: 127.0.0.1

# Port for AcraWebconfig HTTP endpoint
incoming_connection_port: 8000

# Logging format: plaintext, json or CEF
logging_format: plaintext

# Path to static content
static_path: cmd/acra-webconfig/static

