ignore_parse_error: false
parse_errors_log: unparsed_queries.log
capture_log: censor.log
handlers:
  - handler: query_ignore
    queries:
      - ROLLBACK
      - COMMIT
      - BEGIN
  - handler: blacklist
    queries:
      - INSERT INTO SalesStaff1 VALUES (1, 'Stephen', 'Jiang');
      - SELECT AVG(Price) FROM Products;
    tables:
      - EMPLOYEE_TBL
      - Customers
    patterns:
      - SELECT EMP_ID, LAST_NAME FROM EMPLOYEE %%WHERE%%;