version: 0.85.0
# path to config
config_file: 

# Turn on debug logging
d: false

# dump config
dump_config: false

# Auth file
file: configs/auth.keys

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# Folder from which will be loaded keys
keys_dir: .acrakeys

# Key Store format to use: v1 (current), v2 (experimental)
keystore: v1

# Password
password: 

# Remove user
remove: false

# Add/update password for user
set: false

# User
user: 

